sudo: false
services: docker
# undocumented minimum language set
language: generic

env:
  - LLVM_VERSION=4.0

before_install:
  - sudo service docker stop; if [ "$(ls -A /home/travis/docker)" ]; then echo "/home/travis/docker already set"; else sudo mv /var/lib/docker /home/travis/docker; fi
  - sudo bash -c "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -g /home/travis/docker\"' > /etc/default/docker"; sudo service docker start
install:
  - docker build --rm -f docker/base/Dockerfile -t goclang/base .
  - make docker-build
script:
  - make docker-test
before_cache:
  - sudo service docker stop; sudo chown -R travis ~/docker
cache:
  directories:
    ~/docker
